Repository telerik/kendo-themes, pull requests merged in 2020-06, with the labels that each got.

#1576 fix(checkbox): checkbox variables are messing default flag
  packages/default/scss/_variables.scss
Labels: C:Checkbox, bug

#1579 fix(treelist): locked columns overlap toolbar
  packages/default/scss/treelist/_layout.scss
Labels: C:Treelist, FW:React, bug

#1583 fix(dialog): remove focus outline
  packages/default/scss/dialog/_layout.scss
  packages/default/scss/scheduler/_layout.scss
Labels: C:Dialog, C:Scheduler, FW:Angular, FW:React, T:Bootstrap, T:Default, T:Material, bug

#1584 fix(tooltip): add max-width to container
  packages/default/scss/common/_animations.scss
Labels: C:Tooltip, FW:Angular, FW:Blazor, FW:React, FW:jQuery, T:Bootstrap, T:Classic, T:Default, T:Material, bug

#1587 fix: input-group-prepend styling
  packages/default/scss/forms/_layout.scss
Labels: C:Forms, FW:Angular, FW:Blazor, FW:React, FW:jQuery, T:Bootstrap, bug

#1586 chore: add funcitonality to resolve variables values
  gulpfile.js
  package-lock.json
  package.json
Labels: docs, infrastructure, internal

#1591 Upload: add max-height and scroll
  packages/bootstrap/scss/_variables.scss
  packages/default/scss/_variables.scss
  packages/default/scss/upload/_layout.scss
  packages/material/scss/_variables.scss
Labels: C:Upload, test:missing

#1598 fix(contextmenu): menu items cut off
  packages/default/scss/common/_animations.scss
Labels: C:Contextmenu, FW:jQuery, T:Bootstrap, T:Classic, T:Default, T:Material, regression

#1599 fix: add !optional flag to k-text-selection
  packages/bootstrap/scss/scrollview/_theme.scss
  packages/bootstrap/scss/spreadsheet/_theme.scss
  packages/default/scss/adaptive/_theme.scss
  packages/default/scss/breadcrumb/_theme.scss
  packages/default/scss/card/_theme.scss
  packages/default/scss/chat/_theme.scss
  packages/default/scss/colorpicker/_theme.scss
  packages/default/scss/combobox/_theme.scss
  packages/default/scss/common/_base.scss
  packages/default/scss/dataviz/_theme.scss
  packages/default/scss/datetime/_theme.scss
  packages/default/scss/drawer/_theme.scss
  packages/default/scss/dropdownlist/_theme.scss
  packages/default/scss/maskedtextbox/_theme.scss
  packages/default/scss/mediaplayer/_theme.scss
  packages/default/scss/multiselect/_theme.scss
  packages/default/scss/notification/_theme.scss
  packages/default/scss/numerictextbox/_theme.scss
  packages/default/scss/pager/_theme.scss
  packages/default/scss/panelbar/_theme.scss
  packages/default/scss/pdf-viewer/_theme.scss
  packages/default/scss/progressbar/_theme.scss
  packages/default/scss/rating/_theme.scss
  packages/default/scss/scheduler/_theme.scss
  packages/default/scss/scrollview/_theme.scss
  packages/default/scss/splitter/_theme.scss
  packages/default/scss/spreadsheet/_theme.scss
  packages/default/scss/window/_theme.scss
  packages/material/scss/combobox/_theme.scss
  packages/material/scss/datetime/_theme.scss
  packages/material/scss/multiselect/_theme.scss
  packages/material/scss/panelbar/_theme.scss
  packages/material/scss/progressbar/_theme.scss
  packages/material/scss/spreadsheet/_theme.scss
Labels: FW:Angular, FW:Blazor, FW:React, FW:jQuery, T:Bootstrap, T:Classic, T:Default, T:Material, bug

#1601 fix(scheduler): missing border
  packages/default/scss/scheduler/_layout.scss
Labels: C:Scheduler, FW:Angular, FW:Blazor, FW:jQuery, T:Bootstrap, T:Classic, T:Default, T:Material, bug

#1603 fix(calendar): remove outline from today button
  packages/default/scss/calendar/_layout.scss
Labels: C:Calendar, bug

#1605 fix(wizard): content appearance in IE11
  packages/default/scss/wizard/_layout.scss
Labels: C:Wizard, FW:jQuery, T:Bootstrap, T:Default, T:Material, bug

#1622 fix(progressbar): use material-color instead of material-contrast to resolve correct values
  packages/material/scss/_variables.scss
  packages/material/scss/common/material/_themeing.scss
Labels: C:Progressbar, T:Material, bug

#1621 fix(calendar): selected hover cell text color
  packages/default/scss/calendar/_theme.scss
Labels: C:Calendar, bug, test:missing

#1624 fix(chart): chart tooltip should have the same padding as tooltip
  packages/default/scss/dataviz/_layout.scss
Labels: test:missing

#1608 fix(textbox): prevent placeholder selection
  packages/default/scss/input/_layout.scss
Labels: C:Textbox, bug

#1593 Add compilation root tasks
  gulpfile.js
  package-lock.json
  package.json
  packages/theme-tasks/gulpfile.js
  packages/theme-tasks/lib/sassimporter.js
  packages/theme-tasks/package-lock.json
  packages/theme-tasks/package.json
Labels: Enhancement, infrastructure, internal

#1625 Add tooltip dependency to chart
  packages/default/scss/dataviz/_index.scss
Labels: C:Chart, Enhancement

#1614 chore: update lerna to v3
  lerna.json
  package-lock.json
  package.json
  packages/bootstrap/package-lock.json
  packages/default/package-lock.json
  packages/material/package-lock.json
  packages/theme-tasks/package-lock.json
Labels: infrastructure, internal

#1632 infra(lerna): checkout develop before publishing dev relase
  .commitlintrc.json
  build/publish.sh
Labels: infrastructure, internal

#1635 infra(lerna): create explicit version and then publish it
  build/publish.sh
Labels: infrastructure, internal

#1636 infra(lerna): do not generate change log, tags or push on dev release
  build/publish.sh
Labels: infrastructure, internal

#1637 Make lerna work
  build/publish.sh
Labels: infrastructure, internal

#1634 fix(badge): add display for the Angular badge
  packages/default/scss/badge/_layout.scss
Labels: C:Badge, FW:Angular, T:Bootstrap, T:Default, T:Material, test:missing

#1638 revert lerna
  build/publish.sh
  lerna.json
  package-lock.json
  package.json
Labels: infrastructure, internal

#1641 fix(wizard): add button, stepper and form as wizard dependencies
  packages/bootstrap/scss/wizard/_index.scss
  packages/default/scss/wizard/_index.scss
  packages/material/scss/wizard/_index.scss
Labels: C:Wizard

#1645 chore: add dependabot
  .github/dependabot.yml
Labels: infrastructure, internal

#1642 fix(input): remove additional box shadow in Firefox browser
  packages/default/scss/input/_layout.scss
Labels: C:Forms, bug

#1650 Update dependabot.yml
  .github/dependabot.yml
Labels: infrastructure, internal
