Repository telerik/kendo-themes, pull requests merged in 2020-10, with the labels that each got.

#1940 Panelbar: keyboard navigation in IE
  packages/default/scss/panelbar/_layout.scss
Labels: C:Panelbar, bug

#1958 fix(charts): tooltip opacity option not applying
  packages/default/scss/dataviz/_layout.scss
Labels: C:Chart, C:Tooltip, bug, test:missing

#1966 Remove dist folders on clean install
  build/clean.sh
Labels: infrastructure, internal

#1970 add web.config
  web.config
Labels: infrastructure

#1976 fix(progressbar): do not use 0 for default css variable value when di…
  packages/default/scss/progressbar/_layout.scss
Labels: C:Progressbar, bug

#1979 Update critical deps
  package-lock.json
  package.json
Labels: infrastructure, internal

#1930 fix(checkbox): use calc to calculate checkbox dash width
  packages/bootstrap/scss/checkbox/_variables.scss
  packages/classic/scss/checkbox/_variables.scss
  packages/default/scss/checkbox/_variables.scss
  packages/material/scss/checkbox/_variables.scss
Labels: C:Checkbox, bug

#2002 Trigger test results for ff 82
  tests/visual/output/bootstrap/card-custom.png
  tests/visual/output/default/card-custom.png
  tests/visual/output/material/card-custom.png
Labels: internal

#1999 refactor(calendar): scope k-content and k-title
  packages/default/scss/calendar/_layout.scss
  packages/default/scss/calendar/_theme.scss
  packages/material/scss/calendar/_layout.scss
Labels: C:Calendar, Enhancement, FW:Angular, FW:Blazor, FW:React, FW:jQuery, T:Bootstrap, T:Classic, T:Default, T:Material

#2005 Detect jenkins for clean and install jobs
  build/clean.sh
  build/install.sh
Labels: infrastructure, internal

#2010 Migrate travis to github actions
  .github/workflows/branch_push.yml
  .github/workflows/master_dev_push.yml
  .github/workflows/pull_request.yml
  build/clean.sh
  build/install.sh
Labels: infrastructure, internal

#2013 Infra improvements
  build/clean-install.sh
  build/clean.sh
  build/install.sh
  lerna.json
  package.json
  scripts/utils.js
Labels: infrastructure, internal
