Repository telerik/kendo-themes, pull requests merged in 2020-12, with the labels that each got.

#2099 fix(utils): reverse middle pos in rtl
  packages/default/scss/utils/_position.scss
Labels: C:Utils, test:missing

#2102 fix(multicolumncombobox): remove the horizontal scroll from popup
  packages/default/scss/dropdowngrid/_layout.scss
Labels: C:MultiColumnComboBox, Enhancement, FW:React, test:missing

#2096 feat(grid): add focus shadow to the cells on native browser focus
  packages/bootstrap/scss/grid/_theme.scss
  packages/default/scss/grid/_theme.scss
  packages/material/scss/grid/_theme.scss
Labels: C:Gantt, C:Grid, C:Treelist, Enhancement, FW:React, test:missing

#2125 chore(bottom-navigation): remove focus outline
  packages/default/scss/bottom-navigation/_layout.scss
Labels: C:BottomNav

#2124 chore(fab): apply pointer cursor on item
  packages/default/scss/fab/_layout.scss
Labels: C:Fab

#2129 fix: add generic spacer styles
  packages/bootstrap/scss/utils/_index.scss
  packages/bootstrap/scss/utils/_spacer.scss
  packages/classic/scss/utils/_index.scss
  packages/classic/scss/utils/_spacer.scss
  packages/default/scss/utils/_index.scss
  packages/default/scss/utils/_spacer.scss
  packages/material/scss/utils/_index.scss
  packages/material/scss/utils/_spacer.scss
Labels: C:Utils, Enhancement

#2130 fix: add k-input-separator styles
  packages/default/scss/input/_layout.scss
Labels: C:Inputs, C:Utils, Enhancement, test:missing

#2134 fix: add styles for text-theme colors
  packages/default/scss/common/_decoration.scss
Labels: C:Utils, Enhancement, test:missing

#2142 fix: add k-spacer-sized style
  packages/default/scss/utils/_spacer.scss
Labels: C:Utils, Enhancement

#2145 fix: angular scrollview
  packages/default/scss/scrollview/_layout.scss
  packages/default/scss/scrollview/_theme.scss
  tests/visual/scrollview.html
Labels: C:Scrollview, FW:Angular

#2149 fix: add k-text-base color
  packages/default/scss/common/_decoration.scss
Labels: C:Utils, Enhancement

#2153 Constrain circle and square shapes in size
  packages/bootstrap/scss/fab/_variables.scss
  packages/classic/scss/fab/_variables.scss
  packages/default/scss/fab/_layout.scss
  packages/default/scss/fab/_variables.scss
  packages/material/scss/fab/_variables.scss
Labels: C:Fab, Enhancement, test:missing

#2151 fix: update textarea flex options
  packages/default/scss/textarea/_layout.scss
Labels: C:Textarea, Enhancement

#2157 fix(bottom-navigation): remove focus outline and hover decoration
  packages/default/scss/bottom-navigation/_layout.scss
Labels: C:BottomNav, bug

#2160 fix: revert styles for old rendering in Angular
  packages/default/scss/scrollview/_layout.scss
  packages/default/scss/scrollview/_theme.scss
Labels: C:Scrollview, FW:Angular, T:Bootstrap, T:Default, T:Material

#2177 Add utility classes for resizing elements
  packages/bootstrap/scss/utils/_index.scss
  packages/bootstrap/scss/utils/_resize.scss
  packages/classic/scss/utils/_index.scss
  packages/classic/scss/utils/_resize.scss
  packages/default/scss/utils/_index.scss
  packages/default/scss/utils/_resize.scss
  packages/material/scss/utils/_index.scss
  packages/material/scss/utils/_resize.scss
Labels: C:Utils, Enhancement

#2179 Add styles for `k-state-focus` column menu button
  packages/bootstrap/scss/grid/_theme.scss
  packages/default/scss/grid/_theme.scss
  packages/material/scss/grid/_theme.scss
Labels: test:missing

#2181 Filemanager treeview scroll
  packages/default/scss/filemanager/_layout.scss
Labels: test:missing

#2182 Make textbox / textarea inside prompt 100% wide
  packages/default/scss/window/_layout.scss
Labels: test:missing

#2180 Splitbutton in overflow should display its items vertically
  packages/bootstrap/scss/toolbar/_layout.scss
  packages/default/scss/toolbar/_layout.scss
Labels: test:missing

#2183 Add utility classes for order
  packages/bootstrap/scss/utils/_index.scss
  packages/bootstrap/scss/utils/_order.scss
  packages/classic/scss/utils/_index.scss
  packages/classic/scss/utils/_order.scss
  packages/default/scss/utils/_index.scss
  packages/default/scss/utils/_order.scss
  packages/material/scss/utils/_index.scss
  packages/material/scss/utils/_order.scss
Labels: test:missing

#2185 Tooltip content should take all available vertical space
  packages/default/scss/tooltip/_layout.scss
Labels: test:missing

#2186 Мove last cell editor button infront of the cell so it's clickable
  packages/default/scss/spreadsheet/_layout.scss
Labels: test:missing
