Repository telerik/kendo-themes, pull requests merged in 2021-06, with the labels that each got.

#2508 fix(expansionpanel): import missing dependencies
  packages/bootstrap/scss/expansion-panel/_index.scss
  packages/default/scss/expansion-panel/_index.scss
  packages/material/scss/expansion-panel/_index.scss
Labels: bug

#2504 feat(grid): add k-grid-toolbar-bottom styles
  packages/bootstrap/scss/grid/_variables.scss
  packages/classic/scss/grid/_variables.scss
  packages/default/scss/grid/_layout.scss
  packages/default/scss/grid/_variables.scss
  packages/material/scss/grid/_variables.scss
Labels: C:Grid, Enhancement, test:missing

#2529 docs: add step-by-step guide for authoring visual tests
  tests/visual/README.md
Labels: docs

#2532 fix(grid): do not apply pager focus styles on non-navigable grid
  packages/default/scss/grid/_theme.scss
Labels: C:Grid, bug

#2555 Streamline browserlist file
  .browserslistrc
Labels: Enhancement, internal

#2556 fix(upload): wrong button cursor on hover in firefox
  packages/default/scss/upload/_layout.scss
Labels: C:Upload, bug

#2549 docs: fix typo in readme
  README.md
Labels: docs

#2561 Remove usages of extend text-selection
  packages/bootstrap/scss/scrollview/_theme.scss
  packages/bootstrap/scss/spreadsheet/_theme.scss
  packages/default/scss/adaptive/_theme.scss
  packages/default/scss/breadcrumb/_theme.scss
  packages/default/scss/card/_theme.scss
  packages/default/scss/chat/_theme.scss
  packages/default/scss/colorpicker/_theme.scss
  packages/default/scss/combobox/_theme.scss
  packages/default/scss/common/_base.scss
  packages/default/scss/dataviz/_theme.scss
  packages/default/scss/datetime/_theme.scss
  packages/default/scss/drawer/_theme.scss
  packages/default/scss/dropdownlist/_theme.scss
  packages/default/scss/maskedtextbox/_theme.scss
  packages/default/scss/mediaplayer/_theme.scss
  packages/default/scss/multiselect/_theme.scss
  packages/default/scss/notification/_theme.scss
  packages/default/scss/numerictextbox/_theme.scss
  packages/default/scss/pager/_theme.scss
  packages/default/scss/panelbar/_theme.scss
  packages/default/scss/pdf-viewer/_theme.scss
  packages/default/scss/progressbar/_theme.scss
  packages/default/scss/rating/_theme.scss
  packages/default/scss/scheduler/_theme.scss
  packages/default/scss/scrollview/_theme.scss
  packages/default/scss/splitter/_theme.scss
  packages/default/scss/spreadsheet/_theme.scss
  packages/default/scss/taskboard/_theme.scss
  packages/default/scss/window/_theme.scss
  packages/material/scss/progressbar/_theme.scss
  packages/material/scss/spreadsheet/_theme.scss
Labels: Enhancement

#2564 Ship sass swatches source files in dist
  .github/workflows/release_dev.yml
  .github/workflows/release_stable.yml
  gulpfile.js
  package.json
Labels: Enhancement, infrastructure

#2579 Use saparate variables for calendar views cell size
  packages/default/scss/calendar/_layout.scss
Labels: C:Calendar, internal
