Repository telerik/kendo-themes, pull requests merged in 2021-02, with the labels that each got.

#2265 Traling comma breaks build with WebCompiler VS addon
  packages/default/scss/floating-label/_theme.scss
Labels: bug, integration

#2259 chore: update code owners
  CODEOWNERS.md
Labels: internal

#2262 feat(utils): add font-size utils
  packages/default/scss/utils/_text.scss
Labels: C:Utils, Enhancement

#2272 fix: changing step breaks the layout in iOS
  packages/default/scss/stepper/_layout.scss
Labels: C:Stepper, T:Bootstrap, T:Default, bug

#2273 fix(tabstrip): remove at-root rule
  packages/default/scss/tabstrip/_layout.scss
Labels: C:Tabstrip, bug

#2189 infra: add script for generating utils docs
  gulpfile.js
  package-lock.json
  package.json
  packages/default/scss/utils/README.md
  packages/default/scss/utils/_flex.scss
  packages/default/scss/utils/_grid.scss
  packages/default/scss/utils/_resize.scss
  scripts/utils-docs/generate-utils-docs.js
  scripts/utils-docs/templates/README.md.njk
Labels: docs, infrastructure

#2275 fix: long content in item body overflows
  packages/default/scss/tilelayout/_layout.scss
Labels: C:TileLayout, Enhancement, T:Bootstrap, T:Default, T:Material

#2297 Remove unused k-border class
  packages/default/scss/dataviz/_layout.scss
Labels: internal

#2290 fix: incorrect behavior of autofitting in IE and Chrome
  packages/default/scss/grid/_layout.scss
Labels: C:Grid, FW:Angular, T:Bootstrap, T:Default, T:Material, bug

#2264 Use theme tasks as external package
  gulpfile.js
  lib/data-uri.template
  package-lock.json
  package.json
  scripts/sass-assets.js
  scripts/sass-build.js
  scripts/sass-flatten.js
  scripts/sass-importer.js
  scripts/utils.js
Labels: internal

#2303 Reduce color distance in chart component
  packages/default/scss/dataviz/_layout.scss
Labels: C:Chart, Enhancement

#2305 Revert to husky 4.3.8
  package-lock.json
  package.json
Labels: dependencies, integration

#2312 Don't use display grid for expander pages
  tests/visual/expansion-panel-rtl.html
  tests/visual/expansion-panel.html
Labels: internal

#2309 fix: ExpansionPanel with sibling has wrong top margin
  packages/default/scss/expansion-panel/_layout.scss
Labels: C:Expander, T:Bootstrap, T:Default, T:Material, bug

#2318 Add important flag to position utils
  packages/default/scss/utils/_position.scss
Labels: C:Utils, Enhancement

#2319 Add subtle text variable to be used as secondary text
  packages/bootstrap/scss/_variables.scss
  packages/classic/scss/_variables.scss
  packages/default/scss/_variables.scss
  packages/material/scss/_variables.scss
  packages/material/scss/common/material/_palettes.scss
Labels: C:Typography, Enhancement

#2317 Numerictextbox: apply correct min-width to spinner icons
  packages/bootstrap/scss/input/_variables.scss
  packages/classic/scss/input/_variables.scss
  packages/default/scss/input/_variables.scss
  packages/default/scss/numerictextbox/_layout.scss
  packages/material/scss/input/_variables.scss
Labels: C:Numerictextbox, bug

#2321 Expansion-panel: apply correct RTL selectors
  packages/default/scss/expansion-panel/_layout.scss
Labels: C:Expander, bug

#2327 chore: actually name a variable subtle-text in material
  packages/material/scss/_variables.scss
Labels: internal

#2331 Datetime: remove k-select focus outline
  packages/default/scss/datetime/_layout.scss
Labels: C:Dateinput, C:Datepicker, C:Datetimepicker, C:Timepicker, FW:Blazor, bug

#2337 Scheduler: remove k-nav-current focus outline
  packages/default/scss/scheduler/_layout.scss
Labels: C:Scheduler, FW:Blazor, bug
