Repository telerik/kendo-themes, pull requests merged in 2021-11, with the labels that each got.

#2937 Update dependencies
  .husky/commit-msg
  .husky/pre-commit
  .husky/pre-push
  package-lock.json
  package.json
Labels: internal, dependencies

#2944 update dependencies in html package
  packages/html/package-lock.json
  packages/html/package.json
Labels: internal, dependencies

#2929 fix(chip): add k-state-selected class where missed
  packages/default/scss/chip/_layout.scss
  packages/default/scss/chip/_theme.scss
Labels: bug, FW:React, C:Chip

#2963 chore: update spec
  packages/html/src/autocomplete/README.md
  packages/html/src/button/README.md
  packages/html/src/checkbox/README.md
  packages/html/src/combobox/README.md
  packages/html/src/dateinput/README.md
  packages/html/src/datepicker/README.md
  packages/html/src/datetimepicker/README.md
  packages/html/src/dropdownlist/README.md
  packages/html/src/maskedtextbox/README.md
  packages/html/src/numerictextbox/README.md
  packages/html/src/radio/README.md
  packages/html/src/searchbox/README.md
  packages/html/src/textarea/README.md
  packages/html/src/textbox/README.md
  packages/html/src/timepicker/README.md
Labels: internal

#2951 fix: resolve w3c validator errors
  packages/bootstrap/scss/chat/_variables.scss
  packages/classic/scss/chat/_variables.scss
  packages/default/scss/chat/_variables.scss
  packages/default/scss/chip/_variables.scss
  packages/default/scss/filemanager/_theme.scss
  packages/default/scss/toolbar/_layout.scss
  packages/material/scss/chat/_variables.scss
Labels: bug

#2977 chore(docs): change category of accessibility articles
  docs/accessibility/AnimationContainer.md
  docs/accessibility/ArcGauge.md
  docs/accessibility/AutoComplete.md
  docs/accessibility/Button.md
  docs/accessibility/ButtonGroup.md
  docs/accessibility/Calendar.md
  docs/accessibility/Captcha.md
  docs/accessibility/Chart.md
  docs/accessibility/CheckBox.md
  docs/accessibility/ChunkProgressBar.md
  docs/accessibility/CircularGauge.md
  docs/accessibility/ComboBox.md
  docs/accessibility/ContextMenu.md
  docs/accessibility/DateInput.md
  docs/accessibility/DatePicker.md
  docs/accessibility/DateRangePicker.md
  docs/accessibility/DateTimePicker.md
  docs/accessibility/Drawer.md
  docs/accessibility/DropDownList.md
  docs/accessibility/Editor.md
  docs/accessibility/Form.md
  docs/accessibility/Grid.md
  docs/accessibility/LinearGauge.md
  docs/accessibility/ListView.md
  docs/accessibility/Loader.md
  docs/accessibility/LoaderContainer.md
  docs/accessibility/MaskedTextBox.md
  docs/accessibility/Menu.md
  docs/accessibility/MultiSelect.md
  docs/accessibility/Notification.md
  docs/accessibility/NumericTextBox.md
  docs/accessibility/Pager.md
  docs/accessibility/ProgressBar.md
  docs/accessibility/RadialGauge.md
  docs/accessibility/RadioGroup.md
  docs/accessibility/RangeSlider.md
  docs/accessibility/Scheduler.md
  docs/accessibility/Slider.md
  docs/accessibility/Splitter.md
  docs/accessibility/StockChart.md
  docs/accessibility/Switch.md
  docs/accessibility/TabStrip.md
  docs/accessibility/TextArea.md
  docs/accessibility/TextBox.md
  docs/accessibility/TileLayout.md
  docs/accessibility/TimePicker.md
  docs/accessibility/ToggleButton.md
  docs/accessibility/ToolBar.md
  docs/accessibility/Tooltip.md
  docs/accessibility/TreeList.md
  docs/accessibility/TreeView.md
  docs/accessibility/Upload.md
  docs/accessibility/ValidationMessage.md
  docs/accessibility/ValidationSummary.md
  docs/accessibility/ValidationTooltip.md
  docs/accessibility/Window.md
Labels: docs

#2992 fix(color-preview): remove cursor pointer from preview-color element
  packages/default/scss/color-preview/_layout.scss
Labels: C:Colorpicker

#2993 feat(colorgradient): add color contrast svg styles
  packages/default/scss/colorgradient/_layout.scss
Labels: C:Colorpicker

#2994 fix(grid): decrease column menu icon z-index
  packages/default/scss/grid/_layout.scss
Labels: bug, C:Grid, FW:Angular

#2995 fix: add global variables wcag-light and wcag-dark to work with contrast-wcag function
  packages/default/scss/core/functions/_colors.scss
  packages/nouvelle/scss/core/functions/_index.scss
Labels: Enhancement
