Repository telerik/kendo-themes, pull requests merged in 2021-10, with the labels that each got.

#2818 fix(scheduler): react scheduler timeline view cells doesn't render co…
  packages/default/scss/scheduler/_layout.scss
Labels: C:Scheduler, FW:React

#2829 test(multiviewcalendar): update React test to match the component ren…
  tests/visual/src/misc/calendar-range-react.html
Labels: C:MultiviewCalendar, test:added, FW:React

#2842 Update dev dependencies
  package-lock.json
  package.json
Labels: internal, dependencies

#2846 Update deps
  package-lock.json
  package.json
Labels: dependencies

#2849 Tweak visual tests process
  .github/workflows/ci_visual.yml
  build/create-screenshots.sh
  package.json
Labels: internal

#2858 Arrange components in folders
  packages/html/babel.config.js
  packages/html/babel.config.json
  packages/html/src/button/README.md
  packages/html/src/button/button.jsx
  packages/html/src/button/index.js
  packages/html/src/icon/README.md
  packages/html/src/icon/icon.jsx
  packages/html/src/icon/index.js
  packages/html/src/index.js
Labels: internal
