Repository telerik/kendo-themes, pull requests merged in 2022-06, with the labels that each got.

#3651 Use sass-embedded for dart build
  gulpfile.js
  package-lock.json
  package.json
Labels: internal, infra:build

#3653 chore(multiviewcalendar): disable outline of focused element telerik/kendo#15502
  packages/default/scss/calendar/_layout.scss
Labels: bug, C:MultiviewCalendar

#3660 Add fluent readme and license
  CODEOWNERS
  packages/fluent/LICENSE.md
  packages/fluent/README.md
  packages/fluent/docs/_meta.yml
Labels: internal, T:Fluent

#3661 Check if package is private before tagging with latest
  build/tag-stable.sh
Labels: internal

#3676 Deprecate node 12 for ci tests. add node 16
  .github/workflows/ci_dev.yml
  .github/workflows/ci_next.yml
Labels: internal, infra:github
