Repository telerik/kendo-themes, pull requests merged in 2022-05, with the labels that each got.

#3592 Bulk update dependencies
  package-lock.json
  package.json
Labels: dependencies

#3593 Make kendo-popup 'pos: fixed' inside inputs and pickers so it's not clipped by overflow hidden
  packages/default/scss/input/_layout.scss
Labels: C:Popup

#3607 Trigger image tests in firefox 100
  tests/visual/output/bootstrap/misc/card-rtl.png
  tests/visual/output/classic/misc/card-rtl.png
  tests/visual/output/default/misc/card-rtl.png
  tests/visual/output/material/misc/card-rtl.png
Labels: internal

#3614 Regen tests in firefox 100
  tests/visual/output/bootstrap/misc/adaptive-scheduler-agenda.png
  tests/visual/output/bootstrap/misc/adaptive-scheduler-day-resource-group.png
  tests/visual/output/bootstrap/misc/adaptive-scheduler-day.png
  tests/visual/output/bootstrap/misc/adaptive-scheduler-month.png
  tests/visual/output/classic/misc/adaptive-scheduler-agenda.png
  tests/visual/output/classic/misc/adaptive-scheduler-day-resource-group.png
  tests/visual/output/classic/misc/adaptive-scheduler-day.png
  tests/visual/output/classic/misc/adaptive-scheduler-month.png
  tests/visual/output/default/misc/adaptive-scheduler-agenda.png
  tests/visual/output/default/misc/adaptive-scheduler-day-resource-group.png
  tests/visual/output/default/misc/adaptive-scheduler-day.png
  tests/visual/output/default/misc/adaptive-scheduler-month.png
  tests/visual/output/material/misc/adaptive-scheduler-agenda.png
  tests/visual/output/material/misc/adaptive-scheduler-day-resource-group.png
  tests/visual/output/material/misc/adaptive-scheduler-day.png
  tests/visual/output/material/misc/adaptive-scheduler-month.png
Labels: internal

#3608 feat(panelbar): expose $panelbar-border-style variable
  packages/bootstrap/scss/panelbar/_variables.scss
  packages/classic/scss/panelbar/_variables.scss
  packages/default/scss/panelbar/_layout.scss
  packages/default/scss/panelbar/_variables.scss
  packages/material/scss/panelbar/_variables.scss
Labels: C:Panelbar
