Repository telerik/kendo-themes, pull requests merged in 2022-12, with the labels that each got.

#4154 ci: bump node version for publish workflows to 16
  .github/workflows/_prime-cache.yml
  .github/workflows/publish_npm.yml
  .github/workflows/publish_npm_dev.yml
  .github/workflows/publish_nuget.yml
  .github/workflows/publish_swatches.yml
Labels: infra:build

#4156 Update sass-build to allow correct imports from node_modules
  package-lock.json
  package.json
Labels: internal, dependencies

#4161 chore: drop IE support
  packages/default/scss/action-buttons/_layout.scss
  packages/default/scss/bottom-navigation/_theme.scss
  packages/default/scss/button/_layout.scss
  packages/default/scss/card/_layout.scss
  packages/default/scss/chip/_layout.scss
  packages/default/scss/dialog/_layout.scss
  packages/default/scss/grid/_layout.scss
  packages/default/scss/imageeditor/_layout.scss
  packages/default/scss/list/_layout.scss
  packages/default/scss/panelbar/_layout.scss
  packages/default/scss/pdf-viewer/_layout.scss
  packages/default/scss/pivotgrid/_layout.scss
  packages/default/scss/scheduler/_layout.scss
  packages/default/scss/split-button/_layout.scss
  packages/default/scss/tabstrip/_layout.scss
  packages/default/scss/taskboard/_layout.scss
  packages/default/scss/wizard/_theme.scss
  packages/material/scss/forms/_layout.scss
Labels: breaking change

#4129 feat(html-spec): add grid-layout structure
  packages/html-spec/src/grid-layout/grid-layout.json
  packages/html-spec/src/grid-layout/index.js
  packages/html-spec/src/index.js
Labels: Enhancement, internal
