Repository telerik/kendo-themes, pull requests merged in 2022-03, with the labels that each got.

#3419 chore(infra): add gitattributes config
  .gitattributes
Labels: Enhancement, internal, infrastructure

#3404 Add padding when TextArea is used through directive in Angular
  packages/default/scss/input/_layout.scss
Labels: FW:Angular, C:Textarea

#3429 fix(floating-label): allow label to be clickable in order to focus as…
  packages/default/scss/floating-label/_layout.scss
Labels: C:FloatingLabel

#3435 fix(input): allow placeholder text color customization on generic input
  packages/default/scss/input/_layout.scss
Labels: C:Input

#3465 chore: set status before pushing
  .github/workflows/release_stable.yml
Labels: infra:github

#3467 Remove unused dependencies
  package-lock.json
  package.json
Labels: internal, dependencies

#3468 Upgrade package-lock to v2 format
  package-lock.json
Labels: internal

#3480 fix(button): remove forced aspect ratio
  packages/default/scss/button/_layout.scss
Labels: bug, C:Button

#3481 chore: update setup steps in README.md
  README.md
Labels: docs

#3483 chore: update theme tasks to v1.15
  gulpfile.js
  package-lock.json
  package.json
Labels: dependencies, infra:build

#3498 fix(button): allow $kendo-solid-button-shade-function to be customized
  packages/bootstrap/scss/button/_variables.scss
  packages/classic/scss/button/_variables.scss
  packages/default/scss/button/_variables.scss
  packages/material/scss/button/_variables.scss
Labels: C:Button

#3488 fix: add clear button to json option file
  packages/html/utils/component-options.json
Labels: internal
