Repository telerik/kendo-themes, pull requests merged in 2023-10, with the labels that each got.

#4730 fix(spreadsheet): sheets bar overflows past container dimensions
  packages/default/scss/spreadsheet/_layout.scss
  packages/fluent/scss/spreadsheet/_layout.scss
Labels: bug, C:Spreadsheet

#4736 chore(deps): upgrade husky to v8
  .husky/commit-msg
  .husky/pre-commit
  .husky/pre-push
  package-lock.json
  package.json
Labels: dependencies

#4754 fix(dock-manager): fix toolbar buttons padding in fluent
  packages/fluent/scss/dock-manager/_layout.scss
Labels: bug, C:DockManager

#4755 chore(ci): do not use node_modules from cache for publishing
  .github/workflows/publish_npm.yml
  .github/workflows/publish_npm_dev.yml
Labels: dependencies

#4757 chore(ci): do not use node_modules from cache for nuget publish
  .github/workflows/publish_nuget.yml
Labels: dependencies

#4764 fix(slider): missing animation in rtl mode
  packages/default/scss/slider/_layout.scss
Labels: bug, C:Slider
