Repository telerik/kendo-themes, pull requests merged in 2025-09, with the labels that each got.

#5578 Fix ci visuals
  .github/workflows/_detect-html-changes.yml
  .github/workflows/_render-test-pages.yml
  .github/workflows/ci.yml
Labels: Infrastructure

#5602 fix(window): not resizing properly from sides in RTL
  packages/core/scss/components/window/_layout.scss
Labels: Bug, C: Window

#5609 chore(ci): adjust reporter cacheing
  .github/workflows/_package-report.yml
Labels: Infrastructure

#5610 fix(core): no logical properties should be used with cardinal directions
  packages/core/scss/components/gantt/_layout.scss
  packages/core/scss/components/imageeditor/_layout.scss
  packages/core/scss/components/scheduler/_layout.scss
  packages/core/scss/styles/_resizing.scss
Labels: Bug

#5612 chore(ci): revert reporter tolerance
  .github/workflows/_package-report.yml
Labels: Infrastructure
